import datetime
import logging
from dataclasses import dataclass
from typing import Dict, Any

logger = logging.getLogger(__name__)

@dataclass
class RiskLimits:
    max_position_size_pct: float = 0.10  # Max 10% of portfolio in a single position
    max_daily_drawdown_pct: float = 0.05 # Max 5% daily loss before halting trading
    max_leverage: float = 1.0            # No leverage by default
    allow_short_selling: bool = False    # Disable shorting initially for safety

class Guardian:
    """
    The immutable safety layer.
    The LLM Action Agent CANNOT modify this class or bypass its checks.
    All trades generated by the Action Agent must pass through Guardian.
    """
    def __init__(self, limits: RiskLimits = RiskLimits()):
        self.limits = limits
        self._halted = False

    def is_market_open(self, current_time: datetime.datetime = None) -> bool:
        """
        Hard check for market hours (NYSE/NASDAQ).
        Cannot be bypassed by the LLM.
        """
        if current_time is None:
            current_time = datetime.datetime.now()
            
        # Simplified check: Weekdays, 9:30 AM to 4:00 PM EST
        # In a real system, this should use a proper calendar schedule (e.g., pandas_market_calendars)
        if current_time.weekday() > 4: # 5=Sat, 6=Sun
            return False
            
        market_open = datetime.time(9, 30)
        market_close = datetime.time(16, 0)
        
        return market_open <= current_time.time() <= market_close

    def validate_order(self, symbol: str, quantity: float, price: float, portfolio_value: float, current_positions: Dict[str, Any]) -> bool:
        """
        Validates a proposed order against hard risk limits.
        """
        if self._halted:
            logger.error("Guardian: Trading is halted. Order rejected.")
            return False
            
        if not self.is_market_open():
            logger.error("Guardian: Market is closed. Order rejected.")
            return False

        order_value = quantity * price
        
        # 1. Max Position Size Check
        if order_value > portfolio_value * self.limits.max_position_size_pct:
            logger.error(f"Guardian: Order value {order_value} exceeds max position size limit ({portfolio_value * self.limits.max_position_size_pct}).")
            return False
            
        # 2. Short Selling Check
        if quantity < 0 and not self.limits.allow_short_selling:
            logger.error("Guardian: Short selling is currently disabled.")
            return False

        return True
        
    def check_portfolio_health(self, initial_daily_value: float, current_portfolio_value: float) -> bool:
        """
        Checks if the daily drawdown limit has been breached.
        """
        if initial_daily_value <= 0:
            return True
            
        drawdown = (initial_daily_value - current_portfolio_value) / initial_daily_value
        if drawdown >= self.limits.max_daily_drawdown_pct:
            logger.critical(f"Guardian: DAILY DRAWDOWN LIMIT REACHED ({drawdown*100:.2f}%). HALTING TRADING.")
            self._halted = True
            return False
            
        return True
